# Jekyll Config Files
#
name: Steve Kasica
title: Portfolio
repository: swkasica/swkasica.github.io
baseurl: '/'
analytics_code: 'UA-88748945-1'

collections:
    portfolio:
        output: false

permalink: none

# Blog settings
charset: 'utf-8'

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - bin
  
sass:
    sass_dir: _sass
    style: compressed