# Jekyll Config Files
#
first_name: Stephen
last_name: Kasica
title: Stephen Kasica | Portfolio
baseurl: ''
analytics_code: 'UA-88748945-1'

collections:
    projects:
        output: false
        layout: 'fitRows'
        order: 1
    writing:
        output: false
        layout: 'vertical'
        order: 3
    open_source:
        output: false
        layout: 'vertical'
        order: 2

links:
    - href: https://github.com/stvkas
      icon: fa-github
      name: GitHub
    - href: https://medium.com/@stvkas
      icon: fa-medium
      name: Medium
    - href: https://twitter.com/stvkas
      icon: fa-twitter
      name: Twitter
    - href: https://facebook.com/stephen.kasica
      icon: fa-facebook
      name: Facebook
    - href: https://instagram.com/stvkas
      icon: fa-instagram
      name: Instagram
    - href: https://www.linkedin.com/in/kasica/
      icon: fa-linkedin-square
      name: LinkedIn
    - href: https://stackoverflow.com/users/3734991/kas
      icon: fa-stack-overflow
      name: Stack Overflow
    - href: mailto:stephen.kasica@noaa.gov
      icon: fa-envelope
      name: Email
    - href: tel:+13034975447
      icon: fa-phone
      name: Phone

permalink: none

# Blog settings
charset: 'utf-8'

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  
sass:
    sass_dir: _sass
    style: compressed