source "https://rubygems.org"

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
gem "github-pages", group: :jekyll_plugins

# List ruby gems installed when I run jekyll
gem 'activesupport'
gem 'addressable'
gem 'aws-eventstream'
gem 'aws-sdk'
gem 'aws-sdk-core'
gem 'aws-sdk-resources'
gem 'aws-sigv4'
gem 'bigdecimal'
gem 'bundler'
gem 'cmath'
gem 'coffee-script'
gem 'coffee-script-source'
gem 'colorator'
gem 'colored'
gem 'concurrent-ruby'
gem 'configure-s3-website'
gem 'csv'
gem 'date'
gem 'dbm'
gem 'deep_merge'
gem 'did_you_mean', '~> 1.3.0'
gem 'dotenv'
gem 'e2mmap'
gem 'em-websocket'
gem 'etc'
gem 'ethon'
gem 'eventmachine'
gem 'execjs'
gem 'fcntl'
gem 'ffi'
gem 'fiddle'
gem 'fileutils'
gem 'forwardable'
gem 'forwardable-extended'
gem 'gdbm'
gem 'gemoji'
gem 'html-pipeline'
gem 'html-proofer'
gem 'http_parser.rb'
gem 'i18n'
gem 'io-console'
gem 'ipaddr'
gem 'irb'
gem 'jekyll'
gem 'jekyll-coffeescript'
gem 'jekyll-compose'
gem 'jekyll-docs'
gem 'jekyll-feed'
gem 'jekyll-mentions'
gem 'jekyll-paginate'
gem 'jekyll-redirect-from'
gem 'jekyll-sass-converter'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'jekyll-watch'
gem 'jemoji'
gem 'jmespath'
gem 'json'
gem 'kramdown'
gem 'liquid'
gem 'listen'
gem 'logger'
gem 'matrix'
gem 'mercenary'
gem 'mini_portile2'
gem 'minima'
gem 'minitest'
gem 'mutex_m'
gem 'net-telnet'
gem 'nokogiri'
gem 'openssl'
gem 'ostruct'
gem 'parallel'
gem 'pathutil'
gem 'power_assert'
gem 'prime'
gem 'psych'
gem 'public_suffix'
gem 'rainbow'
gem 'rake'
gem 'rb-fsevent'
gem 'rb-inotify'
gem 'rdoc'
gem 'RedCloth'
gem 'rexml'
gem 'rouge'
gem 'rss'
gem 'ruby_dep'
gem 'rubygems-update'
gem 's3_website'
gem 'safe_yaml'
gem 'sass'
gem 'sass-listen'
gem 'sassc'
gem 'scanf'
gem 'sdbm'
gem 'shell'
gem 'stringio'
gem 'strscan'
gem 'sync'
gem 'test-unit'
gem 'thor'
gem 'thread_safe'
gem 'thwait'
gem 'tracer'
gem 'typhoeus'
gem 'tzinfo'
gem 'webrick'
gem 'xmlrpc'
gem 'yell'
gem 'zlib'

#gem 'breakpoint'
#gem 'modular-scale'